### ISSUE TITLE
needs license

### ISSUE THREAD

**Issue by ghost** [wcummings/hostess#1]
project needs a license - suggest Apache 2

**Comment by wcummings** [comment]
lgpl'd

**Comment by ghost** [comment]
hmmm . any chance of Apache 2 ? Was going to use it with Riak core and it's all Apache 2.

**Comment by wcummings** [comment]
@bryanhuntesl sure i didnt think anyone would actually like to use this lol

**Comment by ghost** [comment]
> @bryanhuntesl sure i didnt think anyone would actually like to use this lol

You never know - everything in Erlang/Elixir world tends to be Apache 2 - I also license any open-source code this way - only notable exceptions are ejabberd and propEr

**Comment by wcummings** [comment]
https://github.com/wcummings/hostess/commit/6926ca750fe6da64825064ce259baeddb92ad828

enjoy!

**Comment by ghost** [comment]
much appreciated !
